[workspace]
members = [ "cli", "config" , "runner"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.98"
toml = "0.8.22"
clap = { version = "4.5.39", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
