# Simulate client/server communication over a perfect connection

[params]
timestep.length = 1          
timestep.unit = "s"
timestep.count = 5        
seed = 42                       
root = "~/simulations"  

[channels]

[channels.direct]

[nodes]

[nodes.client]
deployments = [ {} ]

[[nodes.client.protocols]]

name = "client"
runner = "python3"
runner_args = ["client.py"]
outbound = ["direct"]
inbound = ["direct"]


[nodes.server]
deployments = [ {} ]

[[nodes.server.protocols]]

name = "server"
runner = "python3"
runner_args = ["server.py"]
outbound = ["direct"]
inbound = ["direct"]
