[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { path = "../config" }
runner = { path = "../runner" }
fuse = { path = "../fuse" }
tracing = { workspace = true }
thiserror = { workspace = true }

