[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
toml = { workspace = true }
home = { workspace = true }
