[params]
timestep.length = 1
timestep.unit = "ms"
timestep.count = 5000 
# This could also be placed in the "deployments" array as the `start` argument
timestep.start = 2026-02-01T12:00:00-00:00
root = "~/simulations"  

[channels]

[channels.test]
link = "ideal"

[nodes]

[nodes.main]
deployments = [ {} ]

[nodes.main.resources]
clock_rate = 16
clock_units = "Mhz"

[[nodes.main.protocols]]

name = "main"
build = "make"
build_args = ["build"]
runner = "./bin/main"

